TiendaGeek/FrontEnd/Controllers/CarritoController.cs
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace FrontEnd.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ICarritoHelper carritoHelper;

        public CarritoController(ICarritoHelper carritoHelper)
        {
            this.carritoHelper = carritoHelper;
        }

        // GET: Carrito
        public ActionResult Index()
        {
            string usuarioId = User.Identity.Name; // Suponiendo que el usuario está autenticado
            var carrito = carritoHelper.GetCarritoByUsuarioId(usuarioId);
            return View(carrito);
        }

        // GET: Carrito/Details/5
        public ActionResult Details(int id)
        {
            var carrito = carritoHelper.GetCarritoById(id);
            return View(carrito);
        }

        // GET: Carrito/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carrito/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarritoViewModel carrito)
        {
            try
            {
                carritoHelper.CreateCarrito(carrito);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carrito/Edit/5
        public ActionResult Edit(int id)
        {
            var carrito = carritoHelper.GetCarritoById(id);
            return View(carrito);
        }

        // POST: Carrito/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarritoViewModel carrito)
        {
            try
            {
                carritoHelper.UpdateCarrito(carrito);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carrito/Delete/5
        public ActionResult Delete(int id)
        {
            var carrito = carritoHelper.GetCarritoById(id);
            return View(carrito);
        }

        // POST: Carrito/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CarritoViewModel carrito)
        {
            try
            {
                carritoHelper.DeleteCarrito(carrito.Id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carrito/Completed
        public ActionResult Completed()
        {
            string usuarioId = User.Identity.Name; // Suponiendo que el usuario está autenticado
            var completedCarritos = carritoHelper.GetCompletedCarritos(usuarioId);
            return View(completedCarritos);
        }
    }
}

TiendaGeek/FrontEnd/Controllers/CategoriumController.cs
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class CategoriumController : Controller
    {
        private readonly ICategoriumHelper categoriumHelper;

        public CategoriumController(ICategoriumHelper categoriumHelper)
        {
            this.categoriumHelper = categoriumHelper;
        }

        // GET: Categorium
        public ActionResult Index()
        {
            return View(categoriumHelper.GetCategorias());
        }

        // GET: Categorium/Details/5
        public ActionResult Details(int id)
        {
            CategoriumViewModel categorium = categoriumHelper.GetCategoria(id);
            return View(categorium);
        }

        // GET: Categorium/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorium/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriumViewModel categorium)
        {
            try
            {
                _ = categoriumHelper.Add(categorium);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Categorium/Edit/5
        public ActionResult Edit(int id)
        {
            CategoriumViewModel categorium = categoriumHelper.GetCategoria(id);
            return View(categorium);
        }

        // POST: Categorium/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriumViewModel categorium)
        {
            try
            {
                _ = categoriumHelper.Update(categorium);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Categorium/Delete/5
        public ActionResult Delete(int id)
        {
            CategoriumViewModel categorium = categoriumHelper.GetCategoria(id);
            return View(categorium);
        }

        // POST: Categorium/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CategoriumViewModel categorium)
        {
            try
            {
                _ = categoriumHelper.Remove(categorium.CodigoCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


    }
}

TiendaGeek/FrontEnd/Controllers/ContactoController.cs
using FrontEnd.ApiModel;
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class ContactoController : Controller
    {
        //objeto Helper
        private readonly IContactoHelper contactoHelper;

        //constructor
        public ContactoController(IContactoHelper contactoHelper)
        {
            this.contactoHelper = contactoHelper;
        }

        //vista antes de enviar
        public IActionResult Contacto()
        {
            return View();
        }

        //captura datos del form
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Contacto(ContactoViewModel contacto)
        {
            try
            {
                contacto.IdUser = 1; // cambiar cuando funcione el login

                _ = contactoHelper.Add(contacto);


                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacto
        public ActionResult Index()
        {
            return View(contactoHelper.GetContactos());
        }
    }//fn class
}//fn space

TiendaGeek/FrontEnd/Controllers/ProductoController.cs
using FrontEnd.Helpers.Implemetations;
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrontEnd.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoHelper ProductoHelper;
        private readonly ICategoriumHelper CategoriumHelper;
        private readonly IImagenProductoHelper ImagenProductoHelper;

        public ProductoController(IProductoHelper productoHelper, ICategoriumHelper categoriumHelper, IImagenProductoHelper imagenProductoHelper)
        {
            this.ProductoHelper = productoHelper;
            this.CategoriumHelper = categoriumHelper;
            this.ImagenProductoHelper = imagenProductoHelper;
        }

        //index
        public ActionResult Index(string sortOrder, int? categoria)
        {
            List<ProductoViewModel> listaProductos;

            if (categoria.HasValue && categoria.Value > 0)
            {
                listaProductos = ProductoHelper.GetProductosByCategory(categoria.Value);
                ViewBag.CurrentCategoria = categoria.Value;
            }
            else
            {
                listaProductos = ProductoHelper.GetProductos();
                ViewBag.CurrentCategoria = null;
            }

            // Obtener la primera imagen de cada producto o una imagen por defecto
            foreach (var producto in listaProductos)
            {
                var imagenes = ImagenProductoHelper.GetImagenesPorProducto(producto.CodigoProducto);
                if (imagenes != null && imagenes.Any())
                {
                    producto.ImagenPrincipal = imagenes.First().RutaImagen; // Asignar la primera imagen como principal
                }
                else
                {
                    // Asignar una imagen por defecto si no hay imágenes
                    producto.ImagenPrincipal = "~/images/imgNotFound.png";
                }
            }

            switch (sortOrder)
            {
                case "price_asc":
                    listaProductos = listaProductos.OrderBy(p => p.Precio).ToList();
                    break;
                case "price_desc":
                    listaProductos = listaProductos.OrderByDescending(p => p.Precio).ToList();
                    break;
                default:
                    listaProductos = listaProductos.OrderBy(p => p.Nombre).ToList();
                    break;
            }

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CategoriasDisponibles = CategoriumHelper.GetCategorias();

            return View(listaProductos);
        }

        // GET: ProductoController/Details/5
        public ActionResult Details(int id)
        {
            ProductoViewModel producto = ProductoHelper.GetProducto(id);
            if (producto == null)
            {
                return NotFound();
            }

            var imagenesProducto = ImagenProductoHelper.GetImagenesPorProducto(id);

            if (imagenesProducto == null || !imagenesProducto.Any())
            {
                // Asignar una imagen por defecto si no hay imágenes
                producto.Imagenes = new List<ImagenProductoViewModel>
        {
            new ImagenProductoViewModel { RutaImagen = Url.Content("~/images/imgNotFound.png") }
        };
            }
            else
            {
                producto.Imagenes = imagenesProducto;
            }

            return View(producto);
        }


        // GET: ProductoController/Create
        public ActionResult Create()
        {
            ProductoViewModel producto = new ProductoViewModel();
            producto.Categorias = CategoriumHelper.GetCategorias();
            return View(producto);
        }

        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductoViewModel producto)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ProductoHelper.Add(producto);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Error al crear el producto: {ex.Message}");
                }
            }
            producto.Categorias = CategoriumHelper.GetCategorias();
            return View(producto);
        }

        // GET: ProductoController/Edit/5
        public ActionResult Edit(int id)
        {
            ProductoViewModel producto = ProductoHelper.GetProducto(id);
            if (producto == null)
            {
                return NotFound();
            }
            producto.Categorias = CategoriumHelper.GetCategorias();
            return View(producto);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductoViewModel producto)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ProductoHelper.Update(producto);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Error al editar el producto: {ex.Message}");
                }
            }
            producto.Categorias = CategoriumHelper.GetCategorias();
            return View(producto);
        }

        // GET: ProductoController/Delete/5
        public ActionResult Delete(int id)
        {
            ProductoViewModel producto = ProductoHelper.GetProducto(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ProductoViewModel producto)
        {
            try
            {
                ProductoHelper.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error al eliminar el producto: {ex.Message}");
            }
            return View(producto);
        }
    }
}

TiendaGeek/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- Start Header Section -->
    <nav class="custom-navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" class="d-block w-25" alt="..." /></a>

            <div class="collapse navbar-collapse" id="navbarsFurni">
                <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li><a class="nav-link" asp-controller="Producto" asp-action="Index">Productos</a></li>
                        <li><a class="nav-link" asp-controller="Categorium" asp-action="Index">Categoría</a></li>
                        <li><a class="nav-link" asp-controller="Contacto" asp-action="Index">Mensajes</a></li>
                        <li><a class="nav-link" asp-controller="ImagenProducto" asp-action="Index">Imagen</a></li>
                    }
                    else
                    {
                        <li><a class="nav-link" asp-controller="Producto" asp-action="Index">Productos</a></li>
                        <li><a class="nav-link" asp-controller="Contacto" asp-action="Contacto">Contacto</a></li>
                        <!--<li>

                        <a class="nav-link" asp-controller="Carrito" asp-action="Index"> <i class="fa-solid fa-cart-shopping " style="color: #ffffff;"></i></a>

                        </li>-->
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Profile">Mi Perfil</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <button onclick="logout()" class="nav-link btn btn-link" style="color:white;">Cerrar sesión</button>
                        </li>
                        -->
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Inicio sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Registro</a>
                        </li>
                    }
                </ul>
                <!--
                <div class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
                    <div class="nav-item dropdown">
                        <a href="#"
                           class="nav-link"
                           data-bs-toggle="dropdown">
                            <i class="fa-solid fa-user icon"></i>
                        </a>

                        <div class="dropdown-menu m-0 bg-secondary rounded-0">
                            <a class="dropdown-item" asp-controller="Account" asp-action="Login">Inicio sesión</a>
                            <a class="nav-link" asp-controller="Account" asp-action="Register"> Registro</a>
                        </div>
                    </div>
                </div>-->
            </div>
        </div>
    </nav>
    <!-- End Header Section -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Start Footer Section -->
    <footer class="footer-section" style="background-color:black; color:white;">
        <div class="container relative">
            <div class="row g-5 mb-5">
                <div class="col-lg-6">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/logo-maju.png" class="d-block w-25" alt="..." /></a>
                    <p class="mb-4">
                        Buscamos satisfacer tus necesidades, contamos con productos innovadores y originales, que generan una identidad única.
                        En nuestras tiendas podrás encontrar toda clase de figuras de colección exclusivas de TV, anime, cómics entre otras, series de anime en formato DVD, juguetería importada ¡Y mucho más!
                    </p>
                    <ul class="list-unstyled custom-social">
                        <li><a href="https://www.facebook.com"><span class="fa fa-brands fa-facebook-f"></span></a></li>
                        <li><a href="https://twitter.com"><span class="fa fa-brands fa-twitter"></span></a></li>
                        <li><a href="https://www.instagram.com/"><span class="fa fa-brands fa-instagram"></span></a></li>
                        <li><a href="https://cr.linkedin.com/"><span class="fa fa-brands fa-linkedin"></span></a></li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <div class="row links-wrap">
                        <div class="col-6 col-sm-6 col-md-3">
                            <ul class="list-unstyled">
                                <li class="nav-item active">
                                    <a class="nav-link" style="color:white;" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li><a class="nav-link" style="color:white;" asp-controller="Productos" asp-action="Index">Productos</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="border-top copyright">
                    <div class="row pt-4">
                        <div class="col-lg-6">
                            <p class="mb-2 text-center text-lg-start">
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script>. Maju&Manga By <a href="https://themewagon.com">CiudadManga</a>  <!-- License information: https://untree.co/license/ -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer Section -->

    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/tiny-slider.js"></script>
    <script src="js/custom.js"></script>
    <script>
        function logout() {
            // Elimina el token del almacenamiento local
            localStorage.removeItem('token');

            // Opcionalmente, puedes hacer una solicitud al backend si decides implementar la invalidación de tokens en el backend
            fetch('/api/Auth/logout', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ token: getTokenFromStorage() }) // Enviar el token para revocar (opcional)
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Error en la solicitud de revocación del token');
                    }
                    console.log('Token revocado exitosamente');
                })
                .catch(error => {
                    console.error('Error al revocar el token:', error);
                });

            // Redirige al usuario a la página de inicio de sesión
            window.location.href = 'Account/login';
        }

        // Función para obtener el token del almacenamiento local
        function getTokenFromStorage() {
            return localStorage.getItem('token');
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>